### ISSUE TITLE
巴哈登入似乎有問題，至少在使用 Bahamut-Automation@action 的版本時

### ISSUE THREAD

**Issue by SyaoranChang** [JacobLinCool/Bahamut-Automation#10]
你好,

巴哈登入似乎有問題，至少在使用 Bahamut-Automation@action 的版本時
顯示執行 v0.6.8 時，好像一直嘗試登入，但都沒有登入成功

![Snipaste_2021-08-25_12-12-48](https://user-images.githubusercontent.com/18550228/130726118-ad1066a1-babf-4f1c-bdb0-0077bd104ddc.png)

**Comment by SyaoranChang** [comment]
後來我改為手動再執行 JacobLinCool/Bahamut-Automation@v0.6.8
目前自動化有登入成功 再執行的樣子

**Comment by JacobLinCool** [comment]
@SyaoranChang 
感謝回報問題。
在「嘗試登入中」後卡住不常發生，且其原因目前未知，可能是因為 reCAPTCHA。
而 `@action` 版本問題應與 #9 相同。
