### ISSUE TITLE
puppeteer 出錯？

### ISSUE THREAD

**Issue by Slope123** [JacobLinCool/Bahamut-Automation#13]
![image](https://user-images.githubusercontent.com/60516263/132313008-e7dc1287-099a-4450-ba2e-5a3bfd05fe8f.png)

**Comment by cow03haha** [comment]
@Slope123 巴哈登入介面改了導致原本的定位方式出錯，我已經發pr了，等作者處理吧

**Comment by JacobLinCool** [comment]
@Slope123  @cow03haha 
#12 
感謝 @cow03haha 的 PR
