### ISSUE TITLE
您好，目前似乎無法使用 ?

### ISSUE THREAD

**Issue by Charicyukidaru** [JacobLinCool/Bahamut-Automation#15]
我是改到電腦上手動執行的
因為新版沒有附上test.js檔案，所以我從6.8版弄了一個過去
並執行了headless: false來做檢查

我發現6.10版本在登入畫面，並輸入完帳號密碼以及F2A後
他會顯示 "網頁已過期" 或 "帳號密碼錯誤" ，這邊我確定我的帳號密碼都是輸入正確的

回到首頁去，然後又會打開登入畫面
就是一直重複 登入畫面>首頁>登入畫面>首頁 的輪迴

在我把F2A拔掉後也是一樣的情況

後來試著放到Actions上，也是會顯示執行失敗

**Comment by cow03haha** [comment]
我這邊用github action跑是正常的，會不會是被recaptcha擋住

**Comment by JacobLinCool** [comment]
@Charicyukidaru 
我剛剛用 `3220c3f` [編譯過的執行檔](https://github.com/JacobLinCool/Bahamut-Automation/tree/binary) (win) 及 [test.js](https://github.com/JacobLinCool/Bahamut-Automation/blob/main/test.js) (新版也還是有喔，沒有移除) 都可以正常登入。

因為無法重現錯誤，我這邊暫時無法處裡。如有再發生相同問題，請再回覆，謝謝。

**Comment by Charicyukidaru** [comment]
github action對我來說有夠難懂他在跑什麼的
我今天使用執行檔的版本就成功了... 真奇怪，明明設定都一模一樣

那我可以問，新版本的test.js檔跑哪去了嗎?
因為我去Releases抓的zip檔案打開來是沒有的，也不是被防毒之類的刪除
用搜尋只有在node_modules資料夾裡找到好幾個test.js

**Comment by JacobLinCool** [comment]
@Charicyukidaru 
Release 現在應該是用 `action` branch，所以沒有 `test.js`，因為在建構時 ignore 掉了。
但 `main` branch 有，可以在專案根目錄找到。
