### ISSUE TITLE
帳號登入失敗 無法完成兩步驟驗證

### ISSUE THREAD

**Issue by G41imw** [JacobLinCool/Bahamut-Automation#17]
你好 
目前遇到程式無法通過兩步驟的驗證問題
![image](https://user-images.githubusercontent.com/91426767/134818878-131ee614-540f-4cd7-832c-f53afe51e354.png)
此圖被我手動停止
他一直重複這個動作

首先想確認
兩步驟驗證種子碼是在巴哈開啟此設定時
顯示在二維碼旁邊的那串英數字符嗎

第一次設定時我以此為假設填寫設定檔並成功登入
但是當我第二次執行程式時就卡在兩步驟驗證了
巴哈也出現嘗試登錄失敗的通知

經過嘗試：
關閉兩步驟驗證後是可以正常執行並登入的
再次開啟兩步驟驗證並更改設定檔之種子碼又無法登入了
反覆測試數次並沒有變化
已經確定種子碼無誤

(無經驗新手 有烏龍麻煩噴小力點 謝謝)

**Comment by JacobLinCool** [comment]
@G41imw 
謝謝你的測試及回報！

> 首先想確認
> 兩步驟驗證種子碼是在巴哈開啟此設定時
> 顯示在二維碼旁邊的那串英數字符嗎

是的！

---
之前好像巴哈有改過登入介面，當時有稍微修改程式，可能沒有處裡到兩步驟驗證的部分。
因為我個人也沒有啟用兩步驟驗證，所以沒有發現這個問題ˊ。
因最近較為忙碌，待之後有空我會再就此問題做研究。

如有遇到進一步的問題請再於這裡回覆，謝謝。

**Comment by JacobLinCool** [comment]
@G41imw 
你好，
今天早上已經更新程式並處理兩步驟驗證的問題了！
你可以使用 v0.6.12 版本，已經測試過兩步驟驗證可以順利登入。

如果有再遇到問題歡迎再於這裡回覆，謝謝。
