### ISSUE TITLE
觀看雙倍獎勵廣告過程出現錯誤

### ISSUE THREAD

**Issue by HUNGGUO** [JacobLinCool/Bahamut-Automation#20]
![螢幕擷取畫面 2021-10-03 004155](https://user-images.githubusercontent.com/20422763/135725275-4d24ce4e-5515-4aee-902d-f2793292599d.png)

**Comment by bluelovers** [comment]
![image](https://user-images.githubusercontent.com/167966/141303527-96ad6961-0fa3-45cb-bc24-1683f217e8ab.png)

**Comment by wuilliam104286** [comment]
之前用@v0.6.11都沒出問題，直到今天才連續2次出現雙倍獎勵廣告錯誤，只好先把sign module拿掉了
