### ISSUE TITLE
lottery模組運行中的 Cannot read property 'waitForTimeout' of null

### ISSUE THREAD

**Issue by Ning7013** [JacobLinCool/Bahamut-Automation#26]
我是整包抓下來用node.js跑test.js的

直到昨天為止運作都還正常，但今天換日之後，福利社的看影片抽獎都會卡在反白的這一行

![螢幕擷取畫面 2021-11-21 113616](https://user-images.githubusercontent.com/11405761/142748475-74a04160-58a6-4e39-95c2-25bc3b7dd506.jpg)

console中log出來的錯誤是:

  Google AD 處理程式: Start
  Cannot read properties of null (reading 'waitForTimeout')
  Google AD 處理程式: Finished

網頁會在

![螢幕擷取畫面 2021-11-21 113829](https://user-images.githubusercontent.com/11405761/142748526-ba3c0123-b0bc-485b-a99f-ab7df22ed477.jpg)

這個頁面之後就跳出，並且LOG: 

 https://fuli.gamer.com.tw/shop_detail.php?sn=2367#goog_rewarded
  [抽抽樂] 未進入結算頁面，重試中 ✘
  抽抽樂未進入結算頁面

也嘗試重新下載整包code再設定過與重新安裝node,js，還是有一樣的問題，請問有人也碰到同樣的問題嗎?

**Comment by charleschiu2012** [comment]
我遇到這種情況會先手動去巴哈看一次廣告 領取完抽獎券之後再執行script 大多時候就又會正常運行了

**Comment by Ning7013** [comment]
> 我遇到這種情況會先手動去巴哈看一次廣告 領取完抽獎券之後再執行script 大多時候就又會正常運行了

試過了 沒有用...

再測過一陣子之後發現應該是ad_iframe.contentFrame()被assign給ad_frame的時候變成null了，但不知道怎麼解

**Comment by domious4888** [comment]
自從11號後自動化就不跑抽獎了
請問怎麼辦

**Comment by JacobLinCool** [comment]
我在 #31  1.0.0-pre.1 之後改用 Firefox 不知道有沒有辦法解決這個問題。

**Comment by charleschiu2012** [comment]
@JacobLinCool 不好意思如果我是用github action想用1.0.0-pre.1版的話 是重新fork一次Bahamut-Automation-Template嗎 還是workflows內會可以調整設定嗎?(不好意思 對action不太熟

**Comment by JacobLinCool** [comment]
@charleschiu2012 

Template 那邊應該會等正式版才會更新。

目前想用 1.0.0-pre.1 的話，請手動把版本改成 `1.0.0-pre.1 ` 或 `action` ( `action` 會自動用最新版)。
