### ISSUE TITLE
按著教程填入了secrets 執行action報錯

### ISSUE THREAD

**Issue by wubushanyan** [JacobLinCool/Bahamut-Automation#27]
## Build Action
Action failed with "not found deploy key or tokens"

## Build Binary
Action failed with "not found deploy key or tokens"

**Comment by JacobLinCool** [comment]
@wubushanyan 

看起來是 Fork 錯 Repo 了。

該要 Fork 的是 Template: https://github.com/JacobLinCool/Bahamut-Automation-Template

**Comment by wubushanyan** [comment]
> @wubushanyan
> 
> 看起來是 Fork 錯 Repo 了。
> 
> 該要 Fork 的是 Template: https://github.com/JacobLinCool/Bahamut-Automation-Template

謝謝
