### ISSUE TITLE
secret無法輸入

### ISSUE THREAD

**Issue by canvex** [JacobLinCool/Bahamut-Automation#39]
![image](https://user-images.githubusercontent.com/44216326/143898033-523fb3e0-8ac9-449d-a3b7-839fcbd37bab.png)
輸入完裡面還是空的，有換過裝置了

**Comment by charleschiu2012** [comment]
請提供詳細設定和操作過程 大部分人都不會通靈

**Comment by dxball** [comment]
secret 儲存後就看不到之前設定的值了
這是安全性考量

**Comment by canvex** [comment]
![Screenshot_20211130-010624_Chrome](https://user-images.githubusercontent.com/44216326/143911735-719cb577-47ca-4489-88a6-89b4f6ffb276.jpg)
可是他說找不到Username欸，帳號、密碼那些都在產生器複製貼上的

**Comment by makubex2010** [comment]
你要用https://github.com/JacobLinCool/Bahamut-Automation-Template 這個才能使用，他的教學是直接把你導到Bahamut-Automation，那個是他網頁的更新

**Comment by canvex** [comment]
@makubex2010 我這就是在fork過template並在裡面設secrets了耶

**Comment by makubex2010** [comment]
那就可能你的步驟一定有錯，我剛剛去重用都正常

**Comment by canvex** [comment]
> 那就可能你的步驟一定有錯，我剛剛去重用都正常，刪除secrets然後再重新用一次吧

剛剛整個刪掉重新Fork一次就可以用了，可能是檔案沒更新到
謝謝
