### ISSUE TITLE
登入問題

### ISSUE THREAD

**Issue by Amadu1s** [JacobLinCool/Bahamut-Automation#5]
我使用自動化無法登入，是否用了二階段登入認證就無法使用?

**Comment by JacobLinCool** [comment]
是的，目前沒有支援 2FA。

但既然有人遇到這個問題，我應該會列在優先開發。

如果有相關新進度我會再通知，謝謝。

**Comment by JacobLinCool** [comment]
@Amadu1s  我剛才發佈了 v0.6.6 ，現在有支援兩步驟驗證了。
同時，我也更新了 [設定檔產生器](https://jacoblincool.github.io/Bahamut-Automation/config)，增加了兩步驟驗證種子碼欄位。
兩步驟驗證種子碼就是你啟用兩步驟驗證時，QRcode 旁邊的那串字母。
希望這可以解決你的問題，謝謝。
