### ISSUE TITLE
抽獎發生錯誤

### ISSUE THREAD

**Issue by FongMi** [JacobLinCool/Bahamut-Automation#57]
今天凌晨執行時才發生的，之前都沒問題。

```
[ERROR] [福利社] https://fuli.gamer.com.tw/buyD.php?ad=1&sn=2426
   [ERROR] [福利社] page.click: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "#buyD > div.pbox-btn > a"
  selector resolved to visible <a onclick="buy();" class="btn-base c-primary" href…>確認兌換</a>
attempting click action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (484,409)
  element does receive pointer events
  performing click action
  click action done
  waiting for scheduled navigations to finish
============================================================
    at G (/Users/runner/work/_actions/JacobLinCool/Bahamut-Automation/action/lib/modules/lottery/index.js:1:5971)
    at async /Users/runner/work/_actions/JacobLinCool/Bahamut-Automation/action/lib/modules/lottery/index.js:1:3816 ***
  name: 'TimeoutError'
```

**Comment by FongMi** [comment]
測試 1.0.0-pre.4 沒問題
1.0.0-pre.5 才有問題

**Comment by x313256879** [comment]
+1 也是 Timeout 30000ms exceeded

**Comment by makubex2010** [comment]
大家先改用1.0.0-pre.4比較穩定

目前1.0.0-pre.5因作者更新關係導致亂碼無法使用，只能等作者更新

**Comment by JacobLinCool** [comment]
我有檢查了一下[紀錄](https://github.com/JacobLinCool/Bahamut-Automation/compare/af021e4ff65c7130e8a0ade2e213af9ff12107ad...cad113059460023d704c63909a8c9143d3f0f81b)，我在 29 號的更新並沒有直接更動 `lottery` 模組。

檢查完 `core` 的部分後我認為沒有異常，所以問題可能是出在 dependencies 上面，當時[更新了一些 package](https://github.com/JacobLinCool/Bahamut-Automation/commit/cad113059460023d704c63909a8c9143d3f0f81b)。

在更新 package 時，可能 `package-lock.json` 動到什麼了。

另外，雖然更改中也包含使用 `tsup` 替代 `tsc` 構建，但我看嘗試用回 `tsc` 後結果依舊，應該不是 transpiler 的問題。

我測試過 `@955fb50215ce7f039f2642136b341db9603e38e1` 這個 action build 是可以正常執行的。

接下來應該會試 `@4a7777e5071281936d1a03a8c189135be37fddf4` (但我現在抽獎次數用完了，可能要等等)，如果可以執行就確定是在更新 package 時 `package-lock.json` 壞掉了。

**Comment by JacobLinCool** [comment]
我把 `package-lock.json` revert 回去就暫時修好了。
