### ISSUE TITLE
請問 Bahamut-Automation-Template 需要跟著更新嗎?

### ISSUE THREAD

**Issue by SyaoranChang** [JacobLinCool/Bahamut-Automation#6]
你好,

請問 Bahamut-Automation-Template 需要跟著更新嗎?
發現今天似乎都沒有跑自動化的處理
不知道跟這個有關係嗎?  [已知問題 #4 ](https://github.com/JacobLinCool/Bahamut-Automation/issues/4#issue-962802946)
不過我這個帳號用很久了

**Comment by SyaoranChang** [comment]
看到的錯誤
![Snipaste_2021-08-19_23-37-34](https://user-images.githubusercontent.com/18550228/130098696-af25fa56-b0cf-464b-b7cd-628e8c6de928.png)

**Comment by JacobLinCool** [comment]
@SyaoranChang 

這應該不是 #4 中的問題，我記得我從 v0.6.2 之後有修過類似的問題。
建議可以更新成最新版的，雖然有些改動但設定的部分應該可以向下相容。

如果還有遇到問題，請再告知，謝謝。

**Comment by SyaoranChang** [comment]
感謝回應
我重新 fork Bahamut-Automation-Template 再試試看

**Comment by SyaoranChang** [comment]
目前 fork Bahamut-Automation-Template 新版本0.6.9這兩天運作正常
