### ISSUE TITLE
檢測雙倍簽到獎勵錯誤

### ISSUE THREAD

**Issue by FongMi** [JacobLinCool/Bahamut-Automation#62]
1.0.0-pre.5
1.0.0-pre.6
以上版本都會發生

![image](https://user-images.githubusercontent.com/3471963/148145286-91f11ebd-7911-47a5-94a8-6866a8a2560e.png)

![image](https://user-images.githubusercontent.com/3471963/148145447-81370741-8a7c-4252-afff-6f636b3f035c.png)

**Comment by Halcyon9453** [comment]
好像最近常發生這狀況

p.s. 作者說有問題的話要發到 **_Discussions_** 喔
