### ISSUE TITLE
我的帳號沒有啟用 兩步驟驗證，但似乎進去 check2FA 檢查時 twoFA 會是 true

### ISSUE THREAD

**Issue by SyaoranChang** [JacobLinCool/Bahamut-Automation#7]
你好,

我的帳號沒有啟用 兩步驟驗證，但似乎進去 check2FA 檢查時 twoFA 會是 true
不知道這算不算是 Bug?
最後還是有正常登入成功就是了
![Snipaste_2021-08-21_02-16-48](https://user-images.githubusercontent.com/18550228/130277763-7549383f-e2de-4018-b68d-6808f9bcc733.png)

**Comment by JacobLinCool** [comment]
@SyaoranChang 
感謝回報，我看看 2FA 判定是否搞錯了什麼
