### ISSUE TITLE
automation.yml 的 v0.6.9版本內容只有改為 v0.6. 導致自動化無法正常下載

### ISSUE THREAD

**Issue by SyaoranChang** [JacobLinCool/Bahamut-Automation#8]
你好,

automation.yml 的 v0.6.9版本內容只有改為 v0.6. 導致自動化無法正常下載

![](https://user-images.githubusercontent.com/18550228/130277008-c8855735-4c80-4914-a300-17c4e6511d0d.png)

**Comment by JacobLinCool** [comment]
@SyaoranChang 
感謝提醒，已修正。
其實發在 Template 那也可以，不用移過來。
