### ISSUE TITLE
沒有登入成功 卻沒有報錯

### ISSUE THREAD

**Issue by bluelovers** [JacobLinCool/Bahamut-Automation#85]
https://github.com/bluelovers/Bahamut-Automation-Template/runs/5351428585?check_suite_focus=true

![image](https://user-images.githubusercontent.com/167966/155906253-43a0b1c0-7be8-4109-ae4b-ae8639cb5298.png)

**Comment by JacobLinCool** [comment]
嗯，新的版本應該有修復此問題。
